# 4. Numpy Basics:Arrays and Vectorized Computation

In [68]:
import numpy as np
my_arr = np.arange(51)
my_list = list(range(51))
print("My List :",my_list)
#print(my_list)
%time for _ in range(10): my_arr2 = my_arr*2
%time for _ in range(10): my_list2= [x*2 for x in my_list]
print(my_list2)
print(my_arr2)


My List : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
Wall time: 0 ns
Wall time: 0 ns
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### 4.1 : TheNumPy ndarray : A Multidimentional Array Object

In [121]:
import numpy as np
data = np.random.randn(2,3)
print(data)
print(data*10)
print(data+data)
print("Shape of the array:",data.shape)
print(data.dtype) 

### Creating ndarrays :::

data1 = [6,7.5,8,0,1]
arr1=np.array(data1)
print(arr1)
data2 = [[1,2,3,4,],[5,6,7,8]]
arr2 = np.array(data2) #data2 is list of lists(2D)
print(arr2)
m=arr2.ndim
print(m)
print(arr2.shape)
o=arr2.dtype
p=arr1.dtype
print(o,p)
a=np.zeros(10)
print(a)
a=np.zeros((3,6))
print(a)
a=np.zeros((2,3,6))
print(a)
a=np.arange(15)
print(a)
a=np.eye((4))
print(a)

[[-0.83910595 -0.51289283 -0.1965801 ]
 [ 0.43206979  0.36333538  0.55242161]]
[[-8.39105947 -5.12892826 -1.96580096]
 [ 4.32069786  3.63335383  5.52421612]]
[[-1.67821189 -1.02578565 -0.39316019]
 [ 0.86413957  0.72667077  1.10484322]]
Shape of the array: (2, 3)
float64
[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32 float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Data types of ndarrays:

In [150]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([1,2,3],dtype = np.int32)
print(arr1)
print(arr1.dtype)
print(arr2)
print(arr2.dtype)
float_arr2=arr2.astype(np.float64)
print(float_arr2)
print(float_arr2.dtype)
arr4=np.array([3.5,6.5,7.5,8.5])
print(arr4,arr4.dtype)
arr4=arr4.astype(np.int64)
print(arr4,arr4.dtype)
arr5=np.array(["3.5",'6.5','7.5','8.5'],dtype =np.string_)
print(arr5,arr5.dtype)
print(arr5.astype(np.float64))
print(arr5.dtype)


[1. 2. 3.]
float64
[1 2 3]
int32
[1. 2. 3.]
float64
[3.5 6.5 7.5 8.5] float64
[3 6 7 8] int64
[b'3.5' b'6.5' b'7.5' b'8.5'] |S3
[3.5 6.5 7.5 8.5]
|S3
