# 4. Numpy Basics:Arrays and Vectorized Computation

In [3]:
import numpy as np
my_arr = np.arange(51)
my_list = list(range(51))
print("My List :",my_list)
#print(my_list)
%time for _ in range(10): my_arr2 = my_arr*2
%time for _ in range(10): my_list2= [x*2 for x in my_list]
print(my_list2)
print(my_arr2)


My List : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
Wall time: 0 ns
Wall time: 0 ns
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### 4.1 : TheNumPy ndarray : A Multidimentional Array Object

In [11]:
import numpy as np
data=np.random.randn(2,3)
print(data)
print(data*10)
print(data+data)
print("Shape of the array:",data.shape)
print(data.dtype) 

### Creating ndarrays :::

data1 = [6,7.5,8,0,1]
arr1=np.array(data1)
print(arr1)
data2 = [[1,2,3,4,],[5,6,7,8]]
arr2 = np.array(data2) #data2 is list of lists(2D)
print(arr2)
m=arr2.ndim
print(m)
print(arr2.shape)
o=arr2.dtype
p=arr1.dtype
print(o,p)
a=np.zeros(10)
print(a)
a=np.zeros((3,6))
print(a)
a=np.zeros((2,3,6))
print(a)
a=np.ones((2,3,6))
print(a)
a=np.arange(15)
print(a)
a=np.eye((4))
print(a)

[[ 0.44660916  1.33927572 -1.16307576]
 [-0.01755719  0.18676192 -0.5983767 ]]
[[  4.46609165  13.39275722 -11.63075756]
 [ -0.17557191   1.86761923  -5.98376705]]
[[ 0.89321833  2.67855144 -2.32615151]
 [-0.03511438  0.37352385 -1.19675341]]
Shape of the array: (2, 3)
float64
[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32 float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Data types of ndarrays:

In [13]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([1,2,3],dtype = np.int32)
print(arr1)
print(arr1.dtype)
print(arr2)
print(arr2.dtype)
float_arr2=arr2.astype(np.float64)
print(float_arr2)
print(float_arr2.dtype)
arr4=np.array([3.5,6.5,7.5,8.5])
print(arr4,arr4.dtype)
arr4=arr4.astype(np.int64)
print(arr4,arr4.dtype)
arr5=np.array(["3.5",'6.5','7.5','8.5'],dtype =np.string_)
print(arr5,arr5.dtype)
print(arr5.astype(np.float64))
print(arr5.dtype)

### Arithmetic with NumPy Arrays :::

arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr)
print(arr*arr)
print(arr-arr)
print(1/arr)
print(arr**0.5)
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
print(arr2)
print(arr>arr2)


[1. 2. 3.]
float64
[1 2 3]
int32
[1. 2. 3.]
float64
[3.5 6.5 7.5 8.5] float64
[3 6 7 8] int64
[b'3.5' b'6.5' b'7.5' b'8.5'] |S3
[3.5 6.5 7.5 8.5]
|S3
[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[ True False  True]
 [False  True False]]


## Basic Indexing & Slicing :

In [7]:
import numpy as np
arr=np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8]=12
print(arr)
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1]=1234
print(arr)
arr_slice[:]=64
print(arr)
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr[1])  
print(arr[0][2])  #accessing the exact point
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d,arr3d.shape)
print(arr3d[0])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[   0    1    2    3    4   12 1234   12    8    9]
[ 0  1  2  3  4 64 64 64  8  9]
[4. 5. 6.]
3.0
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)
[[1 2 3]
 [4 5 6]]
